Blog/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('blog.urls')),
    url(r'^auth/', include('authorization.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/urls.py
from django.conf.urls import url
from . import views

app_name = 'blog'
urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^post/$', views.PostView.as_view(), name='post'),
    url(r'^post/(?P<pk>[0-9]+)$', views.ShowPost.as_view(), name='certain_post'),
    url(r'^user/(?P<pk>[0-9]+)$', views.ShowUser.as_view(), name='user')
]

blog/models.py
import json
from django.db import models


class Post(models.Model):
    title = models.CharField(max_length=160)
    content = models.TextField()
    date = models.DateTimeField(auto_now_add=True)
    author = models.ForeignKey('authorization.AppUser', related_name='post_author')

    def __str__(self):
        return self.title

    def get_tag_list(self):
        tags = json.loads(self.tags)
        return tags.split()


class Comment(models.Model):
    post = models.ForeignKey('blog.Post', related_name='comment')
    author = models.ForeignKey('authorization.AppUser', related_name='comment_author')
    text = models.CharField(max_length=300)
    date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.text


class Tag(models.Model):
    title = models.CharField(max_length=64)
    posts = models.ManyToManyField(Post, blank=True, related_name='post_tags')

    def __str__(self):
        return self.title

blog/views.py
import json
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.views.generic import View
from django.urls import reverse_lazy, reverse
from django.shortcuts import render, get_object_or_404
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponseRedirect
from hitcount.models import HitCount
from hitcount.views import HitCountMixin

from .models import Post, Tag
from .form import CommentForm, NewPostForm, UploadImage
from authorization.models import AppUser


class IndexView(View):
    template_name = 'blog/index.html'

    def get(self, request, *args, **kwargs):
        user = request.user
        tags = request.GET.get('tags')
        post_list = Post.objects.all().order_by('-date')
        # temp_post = Post.objects.get(pk=1)
        # print(temp_post.tag_posts))

        if tags is not None:
            tag = Tag.objects.get(title=tags).pk
            #post_list = post_list.filter(tags__regex=tags)
            post_list = post_list.filter(post_tags=tag)
        paginator = Paginator(post_list, 4)

        page = request.GET.get('page')
        try:
            posts = paginator.page(page)
        except PageNotAnInteger:
            posts = paginator.page(1)
        except EmptyPage:
            posts = paginator.page(paginator.num_pages)

        return render(request, 'blog/index.html', context={
            'posts': posts,
            'user': user
        })


class ShowPost(LoginRequiredMixin, View):
    login_url = reverse_lazy('authorization:login')
    redirect_field_name = ''

    def get(self, request, *args, **kwargs):
        post = Post.objects.all().get(pk=kwargs['pk'])

        hit_count = HitCount.objects.get_for_object(post)
        HitCountMixin.hit_count(request, hit_count)


        comment_form = CommentForm()

        return render(request, 'blog/show_post.html', context={
            'post': post,
            'comment_form': comment_form
        })

    def post(self, request, *args, **kwargs):
        user = request.user
        post_id = kwargs['pk']
        post = get_object_or_404(Post, pk=post_id)
        comment_form = CommentForm(request.POST)

        if comment_form.is_valid():
            comment = comment_form.save(commit=False)
            comment.post = post
            comment.author = user
            comment.save()
            return HttpResponseRedirect(reverse('blog:certain_post', kwargs={'pk': kwargs['pk']}))


class PostView(LoginRequiredMixin, View):
    login_url = reverse_lazy('authorization:login')
    redirect_field_name = ''

    def get(self, request, *args, **kwargs):
        form = NewPostForm()

        return render(request, 'blog/new_post.html', context={
            'form': form
        })

    def post(self, request, *args, **kwargs):
        user = request.user
        new_post_form = NewPostForm(request.POST)

        if new_post_form.is_valid():
            post = new_post_form.save(commit=False)
            post.author = user
            tags = Tag.objects.filter(pk__in=request.POST.getlist('tags'))
            #post.tags = json.dumps(request.POST.getlist('tags'))
            post.save()
            post.post_tags.add(*tags)

            return HttpResponseRedirect(reverse('blog:index'))


class ShowUser(LoginRequiredMixin, View):
    def get(self, request, *args, **kwargs):
        user = request.user
        form = UploadImage()

        return render(request, 'blog/profile.html', context={
            'user': user,
            'form_img': form
        })

    def post(self, request, *args, **kwargs):
        user = AppUser.objects.get(pk=request.user.pk)
        form = UploadImage(files=request.FILES)
        if form.is_valid():
            user.avatar = request.FILES['file']
            user.save()

        return HttpResponseRedirect('/')

blog/templates/blog/index.html
{% extends 'index.html' %}

{#{% load static %}#}
{% load blog_tags %}

{% block profile_link %}
    {% if user.pk %}
        <a href="{% url 'blog:user' pk=user.pk %}">Profile</a>
    {% endif %}
{% endblock %}

{% block content %}

    <section class="page-posts">
    {% for post in posts %}
          <article class="page-posts__post">
            <header class="post__header">
              <time class="post__header__date" datetime="2016-01-27">
                <span class="datetime__day">{{ post.date|date:'j' }}</span>
                  <span class="datetime__monyear">{{ post.date|date:'F' }} {{ post.date|date:'Y' }}</span>
              </time>
              <div class="post__header__headline">
                <div class="post__header__title">{{ post.title }}</div>
                <div class="post__header__written-by">Written by {{ post.author }}</div>
                <div class="post__header__avatar">
                    {% if post.author.avatar %}
                        <img src="{{ post.author.avatar.url }}" alt="avatar">
                    {% endif %}
                    <div>Views: {{ post.views }}</div>
                </div>
              </div>
            </header>
            <div class="post__text">{{ post.content }}</div>
            <a href="{% url 'blog:certain_post' pk=post.pk %}" class="post__read-more">Read More</a>
            <footer class="post__footer">
                {% for tag in post.post_tags.all %}
                    <div class="post__footer__category">
                        <a href="?{% query_transform request tags=tag.title %}">{{ tag.title }}</a>
                    </div>
                {% endfor %}
{#              {% for tag in post.get_tag_list %}#}
{#                <div class="post__footer__category">#}
{#                    <a href="?{% query_transform request tags=tag %}">{{ tag }}</a>#}
{#                </div>#}
{#              {% endfor %}#}
              <i class="post__icon fa fa-thumb-tack"></i>
            </footer>
          </article>
    {% endfor %}
    </section>

{% endblock %}

{% block pagination %}
    {% if posts.has_previous %}
        <a class="post__read-more" href="?{% query_transform request page=posts.previous_page_number %}">Previous</a>
    {% endif %}
    <span class="post__read-more">{{ posts.number }}</span>
    {% if posts.has_next %}
        <a class="post__read-more" href="?{% query_transform request page=posts.next_page_number %}">Next</a>
    {% endif %}
{% endblock %}

blog/templates/blog/new_post.html
{% extends 'index.html' %}

{% block content %}

    <section class="page-posts">
        <form action="{% url 'blog:post' %}" method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit">Add</button>
        </form>
    </section>

{% endblock %}

blog/templates/blog/profile.html
{% extends 'index.html' %}

{% load static %}

{% block styles %}
    <link rel="stylesheet" href="{% static 'blog/css/style.css' %}">
{% endblock %}

{% block content %}

    <section class="page-posts">
        <div>Profile page</div>
        <div>Name: {{ user.username }}</div>
        {% if user.avatar %}
            <div class="avatar-field">Avatar: <img src="{{ user.avatar.url }}"></div>
        {% endif %}
        <form method="post" action="{% url 'blog:user' pk=user.pk %}" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form_img.as_p }}
            <button type="submit">Upload</button>
        </form>
    </section>

{% endblock %}

blog/templates/blog/show_post.html
{% extends 'index.html' %}

{% load static %}
{% load hitcount_tags %}

{% block title %}
    {{ post.title }}
{% endblock %}

{% block content %}
    <section class="page-posts">
      <article class="page-posts__post">
        <header class="post__header">
          <time class="post__header__date" datetime="2016-01-27">
            <span class="datetime__day">{{ post.date|date:'j' }}</span>
              <span class="datetime__monyear">{{ post.date|date:'F' }} {{ post.date|date:'Y' }}</span>
          </time>
          <div class="post__header__headline">
            <div class="post__header__title">{{ post.title }}</div>
            <div class="post__header__written-by">Written by {{ post.author }}</div>
            <div class="post__header__avatar">
              <img src="{% static "img/avatar.png" %}" alt="avatar">
              <div>{% get_hit_count for post %}</div>
            </div>
          </div>
        </header>
        <div class="post__text">{{ post.content }}</div>
        <footer class="post__footer">
          <div class="post__footer__category">Standart</div>
          <div class="post__footer__category">Status</div>
          <div class="post__footer__category">Comments</div>
          <i class="post__icon fa fa-thumb-tack"></i>
        </footer>
        <div>
            <form action="{% url 'blog:certain_post' pk=post.pk%}" method="post">
                {% csrf_token %}
                {{ comment_form.as_p }}
                <button type="submit">Submit</button>
            </form>
        </div>
        <div>
            {% for comment in post.comment.all %}
                <div>{{ comment.text }}</div>
                <div>Written by{{ comment.author }}</div>
            {% endfor %}
        </div>
      </article>
    </section>

{% endblock %}